services:
  laravel:
    build:
      context: ./satisfication_admin
      dockerfile: Dockerfile
    container_name: satisfication_laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./satisfication_admin:/var/www
    ports:
      - "8000:8000"
    networks:
      - satisfication_network
    command: >

  db:
    image: mysql:latest
    container_name: satisfication_db
    environment:
      #เปลี่ยน Root Password ตามต้องการที่นี่
      MYSQL_ROOT_PASSWORD: Password@1234
      MYSQL_DATABASE: satisfication
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "8010:3306"
    networks:
      - satisfication_network
    restart: always

  rabbitmq:
    env_file: "./satisfication_admin/.env"
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
    # กำหนด Username และ Password ที่นี่
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "8020:5672"
      - "8030:15672"
    networks:
      - satisfication_network
  
volumes:
  laravel-data:

networks:
  satisfication_network:
    driver: bridge
